In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score, train_test_split

In [2]:
trainx = pd.read_csv('C:\\Users\\yunting\\Documents\\GitHub\\E.sun_conpetition\\data_set\\new\\ready_train.csv')
trainy = pd.read_csv('C:\\Users\\yunting\\Documents\\GitHub\\E.sun_conpetition\\data_set\\new\\ready_y.csv')

# 如果數據要減維的做法 PCA

In [4]:
'''
from sklearn.decomposition import PCA
pca = PCA(n_components=295)
df = pd.DataFrame(pca.fit_transform(df))
'''

'\nfrom sklearn.decomposition import PCA\npca = PCA(n_components=295)\ndf = pd.DataFrame(pca.fit_transform(df))\n'

# 標準化

In [3]:
X = preprocessing.scale(trainx)
y = preprocessing.scale(trainy)
X = pd.DataFrame(X)
y = pd.DataFrame(y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


# split

In [4]:
train_X , test_X , train_y, test_y = train_test_split (X , y , test_size = 0.3)

# train

### ElasticNetCV

In [6]:
from sklearn.linear_model import ElasticNetCV

In [7]:
lr = ElasticNetCV(max_iter=5000)

In [8]:
cross_val_score(lr, train_X, train_y, cv=5, n_jobs = -1)

array([0.39528601, 0.18182574, 0.37131724, 0.4515587 , 0.2379777 ])

### KNN

In [6]:
from sklearn.neighbors import KNeighborsRegressor

In [7]:
neigh = KNeighborsRegressor(n_neighbors=22)  #台灣22個區域

In [8]:
cross_val_score(neigh, train_X, train_y, cv=3, n_jobs = -1)

array([0.24711856, 0.15314192, 0.15270896])

### DecisionTree

In [5]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score

In [6]:
treereg = DecisionTreeRegressor()

In [7]:
treelist = list(cross_val_score(treereg, train_X, train_y, cv=10, n_jobs = -1))

In [8]:
print('treelist', treelist)
print('平均:', np.mean(treelist))
print('變異數:', np.var(treelist))

treelist [0.6613738708646111, 0.9197397253135641, 0.6575685016237314, 0.7969969639036694, 0.37278477444993113, 0.9721988941517512, 0.34149379767701293, 0.5546709433482606, 0.7831300196774669, 0.9148855112362733]
平均: 0.697484300224627
變異數: 0.044481873707165547


### Random forest

In [5]:
from sklearn import ensemble

In [ ]:
forest = ensemble.RandomForestRegressor (n_estimators=500)
forestlist = list(cross_val_score(forest, train_X, train_y, cv=3, n_jobs = -1))

In [ ]:
print('平均:', np.mean(forestlist))
print('變異數:', np.var(forestlist))

### SVR

In [ ]:
from sklearn import svm

In [5]:
clf = svm.SVR()

In [6]:
cross_val_score(clf, train_X, train_y, cv=3, n_jobs = -1)

array([0.20481822, 0.27195947, 0.35269845])

### Neural Network

In [9]:
from sklearn import neural_network 

In [10]:
mlp = neural_network.MLPRegressor(hidden_layer_sizes=(10), activation="relu",
                 solver='adam', alpha=0.0001,
                 batch_size='auto', learning_rate="constant",
                 learning_rate_init=0.001,
                 power_t=0.5, tol=1e-4) 

In [11]:
cross_val_score(mlp, train_X, train_y, cv=3, n_jobs = -1)

array([-3.05114223e+02, -5.95537787e+02, -3.94250901e-01])

### xgboost

In [7]:
from xgboost import XGBRFRegressor, XGBRegressor

In [6]:
xgbfr = XGBRFRegressor()

In [8]:
cross_val_score(xgbfr, train_X, train_y, cv=10, n_jobs = -1)

array([0.22714918, 0.53940404, 0.53998502, 0.71904012, 0.47768775,
       0.40224459, 0.25143492, 0.55816407, 0.75835495, 0.59357317])

In [8]:
xgbr = XGBRegressor()

In [ ]:
cross_val_score(xgbr, train_X, train_y, cv=10, n_jobs = -1)