In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, train_test_split

In [2]:
trainx = pd.read_csv('C:\\Users\\yunting\\Documents\\GitHub\\E.sun_conpetition\\data_set\\new\\ready_train.csv')
trainy = pd.read_csv('C:\\Users\\yunting\\Documents\\GitHub\\E.sun_conpetition\\data_set\\new\\ready_y.csv')

# 如果數據要減維的做法 PCA

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components=250)
pcax = pd.DataFrame(pca.fit_transform(trainx))

# 標準化

In [3]:
X = preprocessing.scale(trainx)
y = preprocessing.scale(trainy)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


In [14]:
pcaX = preprocessing.scale(pcax)

# train

### split CV, kf

In [4]:
train_X , test_X , train_y, test_y = train_test_split (X , y , test_size = 0.3)

In [5]:
kf = KFold(n_splits=5, shuffle=False)

### ElasticNetCV

In [15]:
from sklearn.linear_model import ElasticNetCV

In [16]:
lr = ElasticNetCV()

#### CV

In [8]:
cross_val_score(lr, train_X, train_y, cv=5, n_jobs = -1)

array([0.39528601, 0.18182574, 0.37131724, 0.4515587 , 0.2379777 ])

#### kf

In [12]:
scores = []
for train_index, test_index in kf.split(X):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    lr.fit(X_train, y_train)
    scores.append(lr.score(X_test, y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the d

In [25]:
print('scores: ', scores)
print('means: ', np.mean(scores))

scores:  [0.2747724118397914, 0.3407921776038, 0.2636751854101991, 0.5004904694295786, 0.391011665383739]
means:  0.3541483819334216


#### pcaX

In [17]:
pcascores = []
for train_index, test_index in kf.split(pcaX):
    X_train, X_test, y_train, y_test = pcaX[train_index], pcaX[test_index], y[train_index], y[test_index]
    lr.fit(X_train, y_train)
    pcascores.append(lr.score(X_test, y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the d

In [18]:
print('scores: ', pcascores)
print('means: ', np.mean(pcascores))
print('vars:', np.var(pcascores))

scores:  [0.2542482612458281, 0.41213582099144863, 0.22853774864767684, 0.524078614131757, 0.3590856364567285]
means:  0.35561721629468784
vars: 0.011602096264330786


### KNN

In [6]:
from sklearn.neighbors import KNeighborsRegressor

In [7]:
neigh = KNeighborsRegressor(n_neighbors=22)  #台灣22個區域

In [8]:
cross_val_score(neigh, train_X, train_y, cv=3, n_jobs = -1)

array([0.24711856, 0.15314192, 0.15270896])

### DecisionTree

In [19]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score

In [20]:
treereg = DecisionTreeRegressor()

#### cv

In [7]:
treelist = list(cross_val_score(treereg, train_X, train_y, cv=10, n_jobs = -1))

In [8]:
print('treelist', treelist)
print('平均:', np.mean(treelist))
print('變異數:', np.var(treelist))

treelist [0.6613738708646111, 0.9197397253135641, 0.6575685016237314, 0.7969969639036694, 0.37278477444993113, 0.9721988941517512, 0.34149379767701293, 0.5546709433482606, 0.7831300196774669, 0.9148855112362733]
平均: 0.697484300224627
變異數: 0.044481873707165547


#### kf

In [28]:
dscores = []
for train_index, test_index in kf1.split(X):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    treereg.fit(X_train, y_train)
    dscores.append(treereg.score(X_test, y_test))

[-0.4072598176850546,
 0.8255111304496573,
 0.8819129130979454,
 0.5367643584855171,
 0.7732275712732016]

In [29]:
print('dscores: ', dscores)
print('means: ', np.mean(dscores))

dscores:  [-0.4072598176850546, 0.8255111304496573, 0.8819129130979454, 0.5367643584855171, 0.7732275712732016]
means:  0.5220312311242534


#### pcaX

In [23]:
pcadscores = []
for train_index, test_index in kf.split(pcaX):
    X_train, X_test, y_train, y_test = pcaX[train_index], pcaX[test_index], y[train_index], y[test_index]
    treereg.fit(X_train, y_train)
    pcadscores.append(lr.score(X_test, y_test))

In [24]:
print('pcadscores: ', pcadscores)
print('means: ', np.mean(pcadscores))
print('vars:', np.var(pcadscores))

pcadscores:  [0.27848031366670867, 0.43556875568225106, 0.24064036108877773, 0.555315789397841, 0.3590856364567285]
means:  0.3738181712584614
vars: 0.012759440772081904


### Random forest

In [6]:
from sklearn import ensemble

### split CV

In [7]:
forest = ensemble.RandomForestRegressor (n_estimators=500)

In [8]:
forestlist = list(cross_val_score(forest, train_X, train_y, cv=3, n_jobs = -1))
print('平均:', np.mean(forestlist))
print('變異數:', np.var(forestlist))

平均: 0.6385072366876857
變異數: 0.015251825203819824


### split kf

In [10]:
kf2 = KFold(n_splits=5, shuffle=False)
fscores = []
for train_index, test_index in kf2.split(X):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    forest.fit(X_train, y_train)
    fscores.append(forest.score(X_test, y_test))
fscores

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWa

[0.6903221903856596,
 0.8015328044427572,
 0.8265898869211754,
 0.5349557235512746,
 0.8190659923334392]

In [11]:
print('fscores: ', fscores)
print('mean: ', np.mean(fscores))
print('var: ', np.var(fscores))

fscores:  [0.6903221903856596, 0.8015328044427572, 0.8265898869211754, 0.5349557235512746, 0.8190659923334392]
mean:  0.7344933195268611
var:  0.012378989621315551


#### pcaX

In [ ]:
pcafscores = []
for train_index, test_index in kf.split(pcaX):
    X_train, X_test, y_train, y_test = pcaX[train_index], pcaX[test_index], y[train_index], y[test_index]
    forest.fit(X_train, y_train)
    pcadxcores.append(forest.score(X_test, y_test))

In [ ]:
print('平均:', np.mean(pcafscores))
print('變異數:', np.var(pcafscores))

### SVR

In [ ]:
from sklearn import svm

In [5]:
clf = svm.SVR()

In [6]:
cross_val_score(clf, train_X, train_y, cv=3, n_jobs = -1)

array([0.20481822, 0.27195947, 0.35269845])

### Neural Network

In [9]:
from sklearn import neural_network 

In [10]:
mlp = neural_network.MLPRegressor(hidden_layer_sizes=(10), activation="relu",
                 solver='adam', alpha=0.0001,
                 batch_size='auto', learning_rate="constant",
                 learning_rate_init=0.001,
                 power_t=0.5, tol=1e-4) 

In [11]:
cross_val_score(mlp, train_X, train_y, cv=3, n_jobs = -1)

array([-3.05114223e+02, -5.95537787e+02, -3.94250901e-01])

### xgboost

In [28]:
from xgboost import XGBRFRegressor

In [29]:
xgbfr = XGBRFRegressor()

#### CV

In [8]:
cross_val_score(xgbfr, train_X, train_y, cv=10, n_jobs = -1)

array([0.22714918, 0.53940404, 0.53998502, 0.71904012, 0.47768775,
       0.40224459, 0.25143492, 0.55816407, 0.75835495, 0.59357317])

In [11]:
xgbfrcv = np.array([0.22714918, 0.53940404, 0.53998502, 0.71904012, 0.47768775,
       0.40224459, 0.25143492, 0.55816407, 0.75835495, 0.59357317])
print('平均:', np.mean(xgbfrcv))
print('變異數:', np.var(xgbfrcv))

平均: 0.506703781
變異數: 0.027585305059210245


#### kf

In [8]:
xscores = []
for train_index, test_index in kf.split(X):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    xgbfr.fit(X_train, y_train)
    xscores.append(xgbfr.score(X_test, y_test))
xscores

[13:27:47] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[13:31:53] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[13:35:37] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[13:38:47] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[13:41:58] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


[0.5439915547427849,
 0.5001202670920932,
 0.5861665555357221,
 0.4666713593845346,
 0.5941229558116123]

In [9]:
print('平均:', np.mean(xscores))
print('變異數:', np.var(xscores))

平均: 0.5382145385133494
變異數: 0.002405624194559961


#### pcaX

In [31]:
pcadxcores = []
for train_index, test_index in kf.split(pcaX):
    X_train, X_test, y_train, y_test = pcaX[train_index], pcaX[test_index], y[train_index], y[test_index]
    xgbfr.fit(X_train, y_train)
    pcadxcores.append(xgbfr.score(X_test, y_test))

[14:11:01] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:11:49] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:12:41] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:13:26] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:14:10] WARNING: d:\build\xgboost\xgboost-0.90.git\src\objective\regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [34]:
print('平均:', np.mean(pcadxcores))
print('變異數:', np.var(pcadxcores))

平均: 0.4463472881115777
變異數: 0.0063477248187634614
